### ISSUE TITLE
Fix error when pressing "Exit to main menu" menu button in pause menu

### ISSUE THREAD

**Issue by 4lrick** [EIP-SunChaser/SunChaser#24]
**Describe the bug**
When the back to main menu button is pressed, multiple error appears

**To Reproduce**
1. Host/Join a game
2. Toggle the pause menu
3. Press the "Exit to main menu" button
4. See error in the error tab

**Expected behavior**
No error are raised in the error tab

**Screenshots**

![Image](https://github.com/user-attachments/assets/26bab810-5fe6-45b6-979a-a49b4e420809)

**Comment by Leandre17** [comment]
![Image](https://github.com/user-attachments/assets/e1ee50a8-2ede-4622-adaa-ae31870a792e)
the best that can be done in 4.2
