### ISSUE TITLE
Car parts health system

### ISSUE THREAD

**Issue by GaetanRaux** [EIP-SunChaser/SunChaser#61]
- [x] Wheels have life
- [x] When no life the wheel disapear
- [x] Car must react realisticly

**Comment by 4lrick** [comment]
Wheels can be destroyed and the car will react accordingly

![Image](https://github.com/user-attachments/assets/aa35f7f7-cf50-4a6e-acfc-6cd3b7780ace)

**Comment by 4lrick** [comment]
The wheels are detached from the body

![rotate_wheel](https://github.com/user-attachments/assets/a70d355f-35eb-4216-ab0d-d0d4e0adf59c)
